package examen1_miguelrojas;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Menu extends javax.swing.JFrame {

    int opcion = 0;

    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        Alumno_Normal first = new Alumno_Normal(0, 0, "Miguel Rojas", 18, "Ing. Sistemas", "Tegucigalpa", 11941201, "MRojas", "pikachu18");
        listNormalAlum.add(first);
        listUsuarios.add("MRojas");
        listPasswords.add("pikachu18");
        Alumno_Normal second = new Alumno_Normal(0, 0, "Jose Rojas", 23, "Ing. Sistemas", "Tegucigalpa", 1234567, "Jose23Rojas", "tarantino");
        listNormalAlum.add(second);
        listUsuarios.add("Jose23Rojas");
        listPasswords.add("tarantino");

        //Combo Box Add
        DefaultComboBoxModel mod = (DefaultComboBoxModel) cb_alumnos.getModel();
        mod.addElement(first);
        mod.addElement(second);
        cb_alumnos.setModel(mod);
        
        //Inicializar Tutores
        Tutor prim = new Tutor(100, 5, 50, "Robb Stark",27, "Actuacion", "Winterfell", 98765, "King_North", "stark");
        listTutor.add(prim);
        listUsuarios.add("King_North");
        listPasswords.add("stark");
        
        //Combo box Tutor
        DefaultComboBoxModel modelTutor = (DefaultComboBoxModel) cb_tutor.getModel();
        modelTutor.addElement(prim);
        cb_tutor.setModel(mod);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_crearAlumno = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        tf_edad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_carrera = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_lugar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_num_cuenta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pf_password = new javax.swing.JPasswordField();
        jb_salir = new javax.swing.JButton();
        jb_guardarAlumno = new javax.swing.JButton();
        jd_login = new javax.swing.JDialog();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        tf_usernameCheck = new javax.swing.JTextField();
        pf_passwordCheck = new javax.swing.JPasswordField();
        jb_ingresarLogIn = new javax.swing.JButton();
        jb_salirLogIn = new javax.swing.JButton();
        jd_crearExam = new javax.swing.JDialog();
        jd_crearTutor = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        tf_num_cuentaTutor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_usuarioTutor = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tf_nombreTutor = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tf_edadTutor = new javax.swing.JTextField();
        pf_passwordTutor = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        tf_carreraTutor = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tf_lugarTutor = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jb_guardarTutor = new javax.swing.JButton();
        jb_salirTutor = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        tf_clasesTutor = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tf_tutorias_numTutor = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tf_gananciasTutor = new javax.swing.JTextField();
        jd_loginAlumno = new javax.swing.JDialog();
        jLabel24 = new javax.swing.JLabel();
        jb_modificarAlumno = new javax.swing.JButton();
        jb_listarAlumno = new javax.swing.JButton();
        jb_examenesAlumno = new javax.swing.JButton();
        jb_reservar = new javax.swing.JButton();
        jb_hacerExamenAlumno = new javax.swing.JButton();
        jb_logout = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jd_loginTutor = new javax.swing.JDialog();
        jLabel25 = new javax.swing.JLabel();
        jb_modTutor = new javax.swing.JButton();
        jb_listarTutor = new javax.swing.JButton();
        jb_darTutoria = new javax.swing.JButton();
        jb_logoutTutor = new javax.swing.JButton();
        jd_modificarAlumno = new javax.swing.JDialog();
        jLabel32 = new javax.swing.JLabel();
        tf_num_cuentaMOD = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        tf_usuarioMOD = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        tf_nombreMOD = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        tf_edadMOD = new javax.swing.JTextField();
        pf_passwordMOD = new javax.swing.JPasswordField();
        jLabel37 = new javax.swing.JLabel();
        tf_carreraMOD = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jb_salirMOD = new javax.swing.JButton();
        tf_lugarMOD = new javax.swing.JTextField();
        jb_guardarAlumnoMOD = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jd_listarAlumnos = new javax.swing.JDialog();
        jLabel40 = new javax.swing.JLabel();
        cb_alumnos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_alumnos = new javax.swing.JTable();
        jb_limpiarAlumnos = new javax.swing.JButton();
        jb_salirListar = new javax.swing.JButton();
        jd_reservarTutoria = new javax.swing.JDialog();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jb_elegirTutor = new javax.swing.JButton();
        jb_elegirAlumnos = new javax.swing.JButton();
        tf_hora = new javax.swing.JTextField();
        tf_aula = new javax.swing.JTextField();
        tf_dia = new javax.swing.JTextField();
        tf_clase = new javax.swing.JTextField();
        tf_mes = new javax.swing.JTextField();
        tf_anio = new javax.swing.JTextField();
        tf_tema = new javax.swing.JTextField();
        jb_guardarReserva = new javax.swing.JButton();
        jb_salirReserva = new javax.swing.JButton();
        jd_listarTutor = new javax.swing.JDialog();
        jLabel49 = new javax.swing.JLabel();
        cb_tutor = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_tutores = new javax.swing.JTable();
        jb_limpiarTutor = new javax.swing.JButton();
        jb_salTutor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();

        jLabel2.setText("Crear Alumno");

        jLabel4.setText("Nombre");

        jLabel5.setText("Edad");

        jLabel6.setText("Carrera");

        jLabel7.setText("Lugar de Nacimiento");

        jLabel8.setText("Numero de Cuenta");

        jLabel9.setText("Usuario");

        jLabel10.setText("Contraseña");

        jb_salir.setText("Salir");
        jb_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_salirMouseClicked(evt);
            }
        });

        jb_guardarAlumno.setText("Guardar");
        jb_guardarAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarAlumnoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_crearAlumnoLayout = new javax.swing.GroupLayout(jd_crearAlumno.getContentPane());
        jd_crearAlumno.getContentPane().setLayout(jd_crearAlumnoLayout);
        jd_crearAlumnoLayout.setHorizontalGroup(
            jd_crearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearAlumnoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jd_crearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jd_crearAlumnoLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_lugar))
                    .addComponent(jLabel2)
                    .addGroup(jd_crearAlumnoLayout.createSequentialGroup()
                        .addGroup(jd_crearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(86, 86, 86)
                        .addGroup(jd_crearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_crearAlumnoLayout.createSequentialGroup()
                        .addGroup(jd_crearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jd_crearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_num_cuenta)
                            .addComponent(tf_usuario)))
                    .addGroup(jd_crearAlumnoLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(64, 64, 64)
                        .addComponent(pf_password)))
                .addContainerGap(358, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearAlumnoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_guardarAlumno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_salir)
                .addGap(41, 41, 41))
        );
        jd_crearAlumnoLayout.setVerticalGroup(
            jd_crearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearAlumnoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addGroup(jd_crearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_lugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_num_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jd_crearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(pf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jd_crearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_salir)
                    .addComponent(jb_guardarAlumno))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jLabel21.setText("Log In");

        jLabel22.setText("Usuario");

        jLabel23.setText("Contraseńa");

        jb_ingresarLogIn.setText("Ingresar");
        jb_ingresarLogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ingresarLogInMouseClicked(evt);
            }
        });

        jb_salirLogIn.setText("Salir");

        javax.swing.GroupLayout jd_loginLayout = new javax.swing.GroupLayout(jd_login.getContentPane());
        jd_login.getContentPane().setLayout(jd_loginLayout);
        jd_loginLayout.setHorizontalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addGap(45, 45, 45)
                        .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_usernameCheck, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(pf_passwordCheck)))
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jb_ingresarLogIn)
                        .addGap(41, 41, 41)
                        .addComponent(jb_salirLogIn))
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel21)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jd_loginLayout.setVerticalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel21)
                .addGap(60, 60, 60)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tf_usernameCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(pf_passwordCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_ingresarLogIn)
                    .addComponent(jb_salirLogIn))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_crearExamLayout = new javax.swing.GroupLayout(jd_crearExam.getContentPane());
        jd_crearExam.getContentPane().setLayout(jd_crearExamLayout);
        jd_crearExamLayout.setHorizontalGroup(
            jd_crearExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_crearExamLayout.setVerticalGroup(
            jd_crearExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel3.setText("Crear Tutor");

        jLabel11.setText("Numero de Cuenta");

        jLabel12.setText("Nombre");

        jLabel13.setText("Edad");

        jLabel14.setText("Contraseña");

        jLabel15.setText("Carrera");

        jLabel16.setText("Lugar de Nacimiento");

        jLabel17.setText("Usuario");

        jb_guardarTutor.setText("Guardar");
        jb_guardarTutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarTutorMouseClicked(evt);
            }
        });

        jb_salirTutor.setText("Salir");
        jb_salirTutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_salirTutorMouseClicked(evt);
            }
        });

        jLabel18.setText("Clases Impartidas ");

        jLabel20.setText("Tutorias Dadas(Numero)");

        jLabel19.setText("Ganancias");

        javax.swing.GroupLayout jd_crearTutorLayout = new javax.swing.GroupLayout(jd_crearTutor.getContentPane());
        jd_crearTutor.getContentPane().setLayout(jd_crearTutorLayout);
        jd_crearTutorLayout.setHorizontalGroup(
            jd_crearTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearTutorLayout.createSequentialGroup()
                .addGroup(jd_crearTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearTutorLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3))
                    .addGroup(jd_crearTutorLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jd_crearTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jd_crearTutorLayout.createSequentialGroup()
                                .addGroup(jd_crearTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jd_crearTutorLayout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(14, 14, 14))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_crearTutorLayout.createSequentialGroup()
                                        .addGroup(jd_crearTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jd_crearTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_num_cuentaTutor)
                                    .addComponent(tf_usuarioTutor)
                                    .addComponent(tf_nombreTutor)
                                    .addComponent(tf_edadTutor)
                                    .addComponent(tf_carreraTutor)
                                    .addComponent(tf_lugarTutor)
                                    .addComponent(pf_passwordTutor)
                                    .addComponent(tf_clasesTutor)
                                    .addComponent(tf_tutorias_numTutor)
                                    .addComponent(tf_gananciasTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(335, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearTutorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jb_guardarTutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_salirTutor)
                .addGap(31, 31, 31))
        );
        jd_crearTutorLayout.setVerticalGroup(
            jd_crearTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearTutorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(25, 25, 25)
                .addGroup(jd_crearTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_nombreTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_crearTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_edadTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crearTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_carreraTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crearTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf_lugarTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crearTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_num_cuentaTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jd_crearTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tf_usuarioTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_crearTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(pf_passwordTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crearTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tf_clasesTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crearTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tf_tutorias_numTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_crearTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tf_gananciasTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_crearTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_guardarTutor)
                    .addComponent(jb_salirTutor))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel24.setText("Alumno");

        jb_modificarAlumno.setText("Modificar Datos");
        jb_modificarAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modificarAlumnoMouseClicked(evt);
            }
        });

        jb_listarAlumno.setText("Listar Datos");
        jb_listarAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_listarAlumnoMouseClicked(evt);
            }
        });

        jb_examenesAlumno.setText("Ver Examenes");

        jb_reservar.setText("Reservar Tutoria");
        jb_reservar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_reservarMouseClicked(evt);
            }
        });

        jb_hacerExamenAlumno.setText("Hacer Examen");

        jb_logout.setText("Logout");
        jb_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_logoutMouseClicked(evt);
            }
        });

        jLabel26.setText("[1]");

        jLabel27.setText("[2]");

        jLabel28.setText("[3]");

        jLabel29.setText("[4]");

        jLabel30.setText("[5]");

        jLabel31.setText("[6]");

        javax.swing.GroupLayout jd_loginAlumnoLayout = new javax.swing.GroupLayout(jd_loginAlumno.getContentPane());
        jd_loginAlumno.getContentPane().setLayout(jd_loginAlumnoLayout);
        jd_loginAlumnoLayout.setHorizontalGroup(
            jd_loginAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginAlumnoLayout.createSequentialGroup()
                .addGroup(jd_loginAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_loginAlumnoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel24))
                    .addGroup(jd_loginAlumnoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_loginAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_loginAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jb_modificarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_examenesAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_listarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102)
                        .addGroup(jd_loginAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_loginAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jb_reservar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_hacerExamenAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jd_loginAlumnoLayout.setVerticalGroup(
            jd_loginAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginAlumnoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel24)
                .addGap(71, 71, 71)
                .addGroup(jd_loginAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_modificarAlumno)
                    .addComponent(jb_reservar)
                    .addComponent(jLabel26)
                    .addComponent(jLabel29))
                .addGap(30, 30, 30)
                .addGroup(jd_loginAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_hacerExamenAlumno)
                    .addComponent(jLabel30)
                    .addComponent(jb_listarAlumno)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(jd_loginAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_loginAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jb_logout)
                        .addComponent(jLabel31)
                        .addComponent(jLabel28))
                    .addComponent(jb_examenesAlumno))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jLabel25.setText("Tutor");

        jb_modTutor.setText("Modificar");

        jb_listarTutor.setText("Listar");

        jb_darTutoria.setText("Dar Tutoria");

        jb_logoutTutor.setText("Logout");

        javax.swing.GroupLayout jd_loginTutorLayout = new javax.swing.GroupLayout(jd_loginTutor.getContentPane());
        jd_loginTutor.getContentPane().setLayout(jd_loginTutorLayout);
        jd_loginTutorLayout.setHorizontalGroup(
            jd_loginTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginTutorLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jd_loginTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addGroup(jd_loginTutorLayout.createSequentialGroup()
                        .addGroup(jd_loginTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_modTutor)
                            .addComponent(jb_listarTutor))
                        .addGap(79, 79, 79)
                        .addGroup(jd_loginTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_loginTutorLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jb_logoutTutor))
                            .addComponent(jb_darTutoria))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jd_loginTutorLayout.setVerticalGroup(
            jd_loginTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginTutorLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jd_loginTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_modTutor)
                    .addComponent(jb_darTutoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_loginTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_listarTutor)
                    .addComponent(jb_logoutTutor))
                .addGap(131, 131, 131))
        );

        jLabel32.setText("Modificar Alumno");

        jLabel33.setText("Usuario");

        jLabel34.setText("Nombre");

        jLabel35.setText("Edad");

        jLabel36.setText("Contraseña");

        jLabel37.setText("Carrera");

        jLabel38.setText("Lugar de Nacimiento");

        jb_salirMOD.setText("Salir");
        jb_salirMOD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_salirMODMouseClicked(evt);
            }
        });

        jb_guardarAlumnoMOD.setText("Guardar");
        jb_guardarAlumnoMOD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarAlumnoMODMouseClicked(evt);
            }
        });

        jLabel39.setText("Numero de Cuenta");

        javax.swing.GroupLayout jd_modificarAlumnoLayout = new javax.swing.GroupLayout(jd_modificarAlumno.getContentPane());
        jd_modificarAlumno.getContentPane().setLayout(jd_modificarAlumnoLayout);
        jd_modificarAlumnoLayout.setHorizontalGroup(
            jd_modificarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificarAlumnoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jd_modificarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_modificarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jd_modificarAlumnoLayout.createSequentialGroup()
                            .addGroup(jd_modificarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jd_modificarAlumnoLayout.createSequentialGroup()
                                    .addComponent(jLabel38)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_lugarMOD))
                                .addGroup(jd_modificarAlumnoLayout.createSequentialGroup()
                                    .addGroup(jd_modificarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel34)
                                        .addComponent(jLabel35)
                                        .addComponent(jLabel37))
                                    .addGap(86, 86, 86)
                                    .addGroup(jd_modificarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tf_edadMOD, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tf_carreraMOD, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tf_nombreMOD, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jd_modificarAlumnoLayout.createSequentialGroup()
                                    .addGroup(jd_modificarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel39)
                                        .addComponent(jLabel33))
                                    .addGap(18, 18, 18)
                                    .addGroup(jd_modificarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tf_num_cuentaMOD)
                                        .addComponent(tf_usuarioMOD)))
                                .addGroup(jd_modificarAlumnoLayout.createSequentialGroup()
                                    .addComponent(jLabel36)
                                    .addGap(64, 64, 64)
                                    .addComponent(pf_passwordMOD, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_modificarAlumnoLayout.createSequentialGroup()
                            .addComponent(jb_guardarAlumnoMOD)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jb_salirMOD)))
                    .addComponent(jLabel32))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_modificarAlumnoLayout.setVerticalGroup(
            jd_modificarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificarAlumnoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jd_modificarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(tf_nombreMOD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_modificarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(tf_edadMOD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_modificarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(tf_carreraMOD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_modificarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(tf_lugarMOD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_modificarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(tf_num_cuentaMOD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jd_modificarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(tf_usuarioMOD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_modificarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(pf_passwordMOD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jd_modificarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_salirMOD)
                    .addComponent(jb_guardarAlumnoMOD)))
        );

        jLabel40.setText("Alumnos");

        cb_alumnos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cb_alumnos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_alumnosItemStateChanged(evt);
            }
        });

        tabla_alumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "Carrera", "Lugar de Nacimiento", "Numero de Cuenta", "Usuario", "Usuari"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_alumnos);

        jb_limpiarAlumnos.setText("Limpiar");
        jb_limpiarAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_limpiarAlumnosMouseClicked(evt);
            }
        });

        jb_salirListar.setText("Salir");
        jb_salirListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_salirListarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_listarAlumnosLayout = new javax.swing.GroupLayout(jd_listarAlumnos.getContentPane());
        jd_listarAlumnos.getContentPane().setLayout(jd_listarAlumnosLayout);
        jd_listarAlumnosLayout.setHorizontalGroup(
            jd_listarAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listarAlumnosLayout.createSequentialGroup()
                .addGroup(jd_listarAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_listarAlumnosLayout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jLabel40))
                    .addGroup(jd_listarAlumnosLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jd_listarAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_listarAlumnosLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cb_alumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_listarAlumnosLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jb_limpiarAlumnos)
                        .addGap(162, 162, 162)
                        .addComponent(jb_salirListar)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jd_listarAlumnosLayout.setVerticalGroup(
            jd_listarAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listarAlumnosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel40)
                .addGap(26, 26, 26)
                .addComponent(cb_alumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(jd_listarAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_limpiarAlumnos)
                    .addComponent(jb_salirListar))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jLabel41.setText("Reservar Tutoria");

        jLabel42.setText("Hora");

        jLabel43.setText("Aula");

        jLabel44.setText("Dia");

        jLabel45.setText("Clase");

        jLabel46.setText("Mes");

        jLabel47.setText("Año");

        jLabel48.setText("Tema");

        jb_elegirTutor.setText("Tutor");
        jb_elegirTutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_elegirTutorMouseClicked(evt);
            }
        });

        jb_elegirAlumnos.setText("Alumnos");
        jb_elegirAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_elegirAlumnosMouseClicked(evt);
            }
        });

        jb_guardarReserva.setText("Guardar");
        jb_guardarReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarReservaMouseClicked(evt);
            }
        });

        jb_salirReserva.setText("Salir");

        javax.swing.GroupLayout jd_reservarTutoriaLayout = new javax.swing.GroupLayout(jd_reservarTutoria.getContentPane());
        jd_reservarTutoria.getContentPane().setLayout(jd_reservarTutoriaLayout);
        jd_reservarTutoriaLayout.setHorizontalGroup(
            jd_reservarTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_reservarTutoriaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel41)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jd_reservarTutoriaLayout.createSequentialGroup()
                .addGroup(jd_reservarTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_reservarTutoriaLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jd_reservarTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel43)
                            .addComponent(jLabel42)
                            .addComponent(jLabel44)
                            .addComponent(jLabel45)
                            .addComponent(jLabel46)
                            .addComponent(jLabel47)
                            .addComponent(jLabel48))
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_reservarTutoriaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jb_elegirTutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jd_reservarTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_elegirAlumnos)
                    .addComponent(tf_tema, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(tf_anio)
                    .addComponent(tf_mes)
                    .addComponent(tf_clase)
                    .addComponent(tf_dia)
                    .addComponent(tf_aula)
                    .addComponent(tf_hora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(jb_guardarReserva)
                .addGap(18, 18, 18)
                .addComponent(jb_salirReserva)
                .addGap(43, 43, 43))
        );
        jd_reservarTutoriaLayout.setVerticalGroup(
            jd_reservarTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_reservarTutoriaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel41)
                .addGap(35, 35, 35)
                .addGroup(jd_reservarTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(tf_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_reservarTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(tf_aula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jd_reservarTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel44)
                    .addComponent(tf_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_reservarTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel45)
                    .addComponent(tf_clase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_reservarTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46)
                    .addComponent(tf_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_reservarTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel47)
                    .addComponent(tf_anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jd_reservarTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_reservarTutoriaLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel48))
                    .addGroup(jd_reservarTutoriaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_tema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jd_reservarTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_reservarTutoriaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jd_reservarTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_elegirTutor)
                            .addComponent(jb_elegirAlumnos))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_reservarTutoriaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(jd_reservarTutoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_guardarReserva)
                            .addComponent(jb_salirReserva))
                        .addGap(39, 39, 39))))
        );

        jLabel49.setText("Listar Tutores");

        cb_tutor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_tutorItemStateChanged(evt);
            }
        });

        tabla_tutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "Carrera", "Lugar de Nacimiento", "Numero de Cuenta", "Usuario", "Password", "Ganancias", "Tutorias Dadas", "Nivel de ensenanza"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla_tutores);

        jb_limpiarTutor.setText("Limpiar");
        jb_limpiarTutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_limpiarTutorMouseClicked(evt);
            }
        });

        jb_salTutor.setText("Salir");
        jb_salTutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_salTutorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_listarTutorLayout = new javax.swing.GroupLayout(jd_listarTutor.getContentPane());
        jd_listarTutor.getContentPane().setLayout(jd_listarTutorLayout);
        jd_listarTutorLayout.setHorizontalGroup(
            jd_listarTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listarTutorLayout.createSequentialGroup()
                .addGroup(jd_listarTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_listarTutorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cb_tutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_listarTutorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_listarTutorLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jb_limpiarTutor)
                        .addGap(93, 93, 93)
                        .addComponent(jb_salTutor))
                    .addGroup(jd_listarTutorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel49)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jd_listarTutorLayout.setVerticalGroup(
            jd_listarTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listarTutorLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel49)
                .addGap(18, 18, 18)
                .addComponent(cb_tutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jd_listarTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_limpiarTutor)
                    .addComponent(jb_salTutor))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menu Principal");

        jToggleButton1.setText("Crear Cuenta");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });

        jToggleButton2.setText("Log in");
        jToggleButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton2MouseClicked(evt);
            }
        });

        jToggleButton3.setText("Crear Examen");
        jToggleButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jToggleButton3)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2)
                    .addComponent(jToggleButton3))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        // TODO add your handling code here:
        try {
            int opcion = Integer.parseInt(JOptionPane.showInputDialog(this, "Escoja un alumno\n[1] Alumno Normal\n[2] Tutor"));
            if (opcion == 1) {
                jd_crearAlumno.setModal(true);
                jd_crearAlumno.pack();
                jd_crearAlumno.setLocationRelativeTo(this);
                jd_crearAlumno.setVisible(true);
            } else {
                jd_crearTutor.setModal(true);
                jd_crearTutor.pack();
                jd_crearTutor.setLocationRelativeTo(this);
                jd_crearTutor.setVisible(true);
            }
        } catch (Exception e) {
            System.out.println("El sistema se ha caido :(");
        }


    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void jToggleButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton2MouseClicked
        // TODO add your handling code here:
        jd_login.setModal(true);
        jd_login.pack();
        jd_login.setLocationRelativeTo(this);
        jd_login.setVisible(true);
    }//GEN-LAST:event_jToggleButton2MouseClicked

    private void jToggleButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton3MouseClicked
        // TODO add your handling code here:
        jd_crearExam.setModal(true);
        jd_crearExam.pack();
        jd_crearExam.setLocationRelativeTo(this);
        jd_crearExam.setVisible(true);
    }//GEN-LAST:event_jToggleButton3MouseClicked

    private void jb_guardarAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarAlumnoMouseClicked
        // TODO add your handling code here:
        try {
            //Valores Generales
            String nombre = "", carrera = "", lugar_nacimiento = "", usuario = "", contrasena = "";
            int edad, num_cuenta;
            //Valores de Alumno Normal
            int conocimiento_acum = 0;
            int nivel_aprendizaje = 0;
            //Conseguir los Valores
            nombre = tf_nombre.getText();
            edad = Integer.parseInt(tf_edad.getText());
            carrera = tf_carrera.getText();
            lugar_nacimiento = tf_lugar.getText();
            num_cuenta = Integer.parseInt(tf_num_cuenta.getText());
            usuario = tf_usuario.getText();
            contrasena = pf_password.getText();

            Alumno_Normal alumNorm = new Alumno_Normal(conocimiento_acum, nivel_aprendizaje, nombre, edad, carrera, lugar_nacimiento, num_cuenta, usuario, contrasena);
            listNormalAlum.add(alumNorm);
            listUsuarios.add(usuario);
            listPasswords.add(contrasena);
            //Combo box
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_alumnos.getModel();
            modelo.addElement(alumNorm);
            cb_alumnos.setModel(modelo);

            //
            //Vaciar textfield
            tf_nombre.setText("");
            tf_edad.setText("");
            tf_carrera.setText("");
            tf_lugar.setText("");
            tf_num_cuenta.setText("");
            tf_usuario.setText("");
            pf_password.setText("");
            JOptionPane.showMessageDialog(this, "Se creo con exito al Alumno");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "El Programa encontro un error fatal");
        }
        jd_crearAlumno.dispose();
    }//GEN-LAST:event_jb_guardarAlumnoMouseClicked

    private void jb_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_salirMouseClicked
        // TODO add your handling code here:
        jd_crearAlumno.dispose();
    }//GEN-LAST:event_jb_salirMouseClicked

    private void jb_guardarTutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarTutorMouseClicked
        // TODO add your handling code here:

        try {
            String nombreTutor = "", carreraTutor = "", lugar_nacimientoTutor = "", usuarioTutor = "", contrasenaTutor = "", clases = "";
            int edad_Tutor, num_cuentaTutor, ganancias, num_tutorias;

            nombreTutor = tf_nombreTutor.getText();
            edad_Tutor = Integer.parseInt(tf_edadTutor.getText());
            carreraTutor = tf_carreraTutor.getText();
            lugar_nacimientoTutor = tf_lugarTutor.getText();
            num_cuentaTutor = Integer.parseInt(tf_num_cuentaTutor.getText());
            usuarioTutor = tf_usuarioTutor.getText();
            contrasenaTutor = pf_passwordTutor.getText();
            clases = tf_clasesTutor.getText();
            num_tutorias = Integer.parseInt(tf_tutorias_numTutor.getText());
            ganancias = Integer.parseInt(tf_gananciasTutor.getText());
            int nivel_ensenanza = 0;

            Tutor tu = new Tutor(ganancias, num_tutorias, nivel_ensenanza, nombreTutor, edad_Tutor, carreraTutor, lugar_nacimientoTutor, num_cuentaTutor, usuarioTutor, contrasenaTutor);
            listTutor.add(tu);
            listUsuarios.add(usuarioTutor);
            listPasswords.add(contrasenaTutor);

            //Vaciar los TextFields
            tf_nombreTutor.setText("");
            tf_edadTutor.setText("");
            tf_carreraTutor.setText("");
            tf_lugarTutor.setText("");
            tf_num_cuentaTutor.setText("");
            tf_usuarioTutor.setText("");
            pf_passwordTutor.setText("");
            tf_clasesTutor.setText("");
            tf_tutorias_numTutor.setText("");
            tf_gananciasTutor.setText("");
            JOptionPane.showMessageDialog(this, "Se creo con exito al Alumno");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "El Programa encontro un error fatal");
        }
        jd_crearTutor.dispose();
    }//GEN-LAST:event_jb_guardarTutorMouseClicked

    private void jb_salirTutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_salirTutorMouseClicked
        // TODO add your handling code here:
        jd_crearTutor.dispose();
    }//GEN-LAST:event_jb_salirTutorMouseClicked

    private void jb_ingresarLogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ingresarLogInMouseClicked
        // TODO add your handling code here:

        String usuarioCheck = "";
        String passwordCheck = "";
        usuarioCheck = tf_usernameCheck.getText();
        passwordCheck = pf_passwordCheck.getText();

        for (int i = 0; i < listUsuarios.size(); i++) {
            for (int j = 0; j < listPasswords.size(); j++) {
                if (!usuarioCheck.equals(listUsuarios.get(i))) {
                    JOptionPane.showMessageDialog(this, "El usuario es incorrecto o no existe");
                    break;
                } else if (!passwordCheck.equals(listPasswords.get(i))) {
                    JOptionPane.showMessageDialog(this, "La Contraseña es incorrecta o no existe");
                    break;
                } else {
                    JOptionPane.showMessageDialog(this, "Ingreso con exito");
                    jd_login.dispose();
                    tf_usernameCheck.setText("");
                    pf_passwordCheck.setText("");
                    for (int k = 0; k < listNormalAlum.size(); k++) {
                        if (usuarioCheck.equals(listNormalAlum.get(i).getUsuario())) {
                            jd_loginAlumno.setModal(true);
                            jd_loginAlumno.pack();
                            jd_loginAlumno.setLocationRelativeTo(this);
                            jd_loginAlumno.setVisible(true);
                        } else {
                            jd_loginTutor.setModal(true);
                            jd_loginTutor.pack();
                            jd_loginTutor.setLocationRelativeTo(this);
                            jd_loginTutor.setVisible(true);

                        }
                    }

                }
            }
        }


    }//GEN-LAST:event_jb_ingresarLogInMouseClicked

    private void jb_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_logoutMouseClicked
        // TODO add your handling code here:
        jd_login.dispose();
        jd_loginAlumno.dispose();
    }//GEN-LAST:event_jb_logoutMouseClicked

    private void jb_modificarAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modificarAlumnoMouseClicked
        // TODO add your handling code here:
        for (int i = 0; i < listNormalAlum.size(); i++) {
            JOptionPane.showMessageDialog(this, "Alumno a Modificar\n" + "[" + i + "]" + listNormalAlum.get(i).getNombre());
        }
        opcion = Integer.parseInt(JOptionPane.showInputDialog(this, "Eliga una opcion"));

        int edadOld = listNormalAlum.get(opcion).getEdad();
        String edadOG = String.valueOf(edadOld);
        int num = listNormalAlum.get(opcion).getNum_cuenta();
        String num_cuentaOG = String.valueOf(num);
        tf_nombreMOD.setText("");
        tf_nombreMOD.setText(listNormalAlum.get(opcion).getNombre());
        tf_edadMOD.setText(edadOG);
        tf_carreraMOD.setText(listNormalAlum.get(opcion).getCarrera());
        tf_lugarMOD.setText(listNormalAlum.get(opcion).getLugar_nacimiento());
        tf_num_cuentaMOD.setText(num_cuentaOG);
        tf_usuarioMOD.setText(listNormalAlum.get(opcion).getUsuario());
        pf_passwordMOD.setText(listNormalAlum.get(opcion).getContrasena());

        jd_modificarAlumno.setModal(true);
        jd_modificarAlumno.pack();
        jd_modificarAlumno.setLocationRelativeTo(this);
        jd_modificarAlumno.setVisible(true);


    }//GEN-LAST:event_jb_modificarAlumnoMouseClicked

    private void jb_salirMODMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_salirMODMouseClicked
        // TODO add your handling code here:
        jd_modificarAlumno.dispose();
    }//GEN-LAST:event_jb_salirMODMouseClicked

    private void jb_guardarAlumnoMODMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarAlumnoMODMouseClicked
        // TODO add your handling code here:
        try {
            String nombreNew = "";
            int edadNew;
            String carreraNew = "";
            String lugarNew = "";
            int num_CuentaNew;
            String usuario = "";
            String password = "";

            //Cambio
            nombreNew = tf_nombreMOD.getText();
            edadNew = Integer.parseInt(tf_edadMOD.getText());
            carreraNew = tf_carreraMOD.getText();
            lugarNew = tf_lugarMOD.getText();
            num_CuentaNew = Integer.parseInt(tf_num_cuentaMOD.getText());
            usuario = tf_usuarioMOD.getText();
            password = pf_passwordMOD.getText();

            if (nombreNew.equals(listNormalAlum.get(opcion).getNombre())) {
                //do nothing
            } else {
                listNormalAlum.get(opcion).setNombre(nombreNew);
            }

            if (edadNew == listNormalAlum.get(opcion).getEdad()) {
                //do nothing
            } else {
                listNormalAlum.get(opcion).setEdad(edadNew);
            }

            if (carreraNew.equals(listNormalAlum.get(opcion).getCarrera())) {
                //do nothing
            } else {
                listNormalAlum.get(opcion).setCarrera(carreraNew);
            }

            if (lugarNew.equals(listNormalAlum.get(opcion).getLugar_nacimiento())) {
                //do nothing
            } else {
                listNormalAlum.get(opcion).setLugar_nacimiento(lugarNew);
            }

            if (num_CuentaNew == listNormalAlum.get(opcion).getNum_cuenta()) {
                //do nothing
            } else {
                listNormalAlum.get(opcion).setNum_cuenta(num_CuentaNew);
            }

            if (usuario.equals(listNormalAlum.get(opcion).getUsuario())) {
                //do nothing
            } else {
                listNormalAlum.get(opcion).setUsuario(usuario);
            }

            if (password.equals(listNormalAlum.get(opcion).getContrasena())) {
                //do nothing 
            } else {
                listNormalAlum.get(opcion).setContrasena(password);
            }

            JOptionPane.showMessageDialog(this, "Se modifico con exito el Alumno");

            tf_nombreMOD.setText("");
            tf_nombreMOD.setText("");
            tf_edadMOD.setText("");
            tf_carreraMOD.setText("");
            tf_lugarMOD.setText("");
            tf_num_cuentaMOD.setText("");
            tf_usuarioMOD.setText("");
            pf_passwordMOD.setText("");
            jd_modificarAlumno.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error fatal");
        }

    }//GEN-LAST:event_jb_guardarAlumnoMODMouseClicked

    private void jb_listarAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_listarAlumnoMouseClicked
        // TODO add your handling code here:
        jd_loginAlumno.dispose();
        jd_listarAlumnos.setModal(true);
        jd_listarAlumnos.pack();
        jd_listarAlumnos.setLocationRelativeTo(this);
        jd_listarAlumnos.setVisible(true);

    }//GEN-LAST:event_jb_listarAlumnoMouseClicked

    private void cb_alumnosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_alumnosItemStateChanged
        // TODO add your handling code here:

        if (evt.getStateChange() == 2) {
            Alumno_Normal an = (Alumno_Normal) cb_alumnos.getSelectedItem();

            Object[] row = {an.getNombre(), an.getEdad(), an.getCarrera(), an.getLugar_nacimiento(), an.getNum_cuenta(), an.getUsuario(), an.getContrasena()};
            DefaultTableModel model = (DefaultTableModel) tabla_alumnos.getModel();
            model.addRow(row);
            tabla_alumnos.setModel(model);
        }
    }//GEN-LAST:event_cb_alumnosItemStateChanged

    private void jb_limpiarAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_limpiarAlumnosMouseClicked
        // TODO add your handling code here:
        tabla_alumnos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre", "Edad", "Carrera", "Lugar de Nacimiento", "Numero de Cuenta", "Usuario", "Usuari"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{false, false, false, false, false, false, false, false};
        });
    }//GEN-LAST:event_jb_limpiarAlumnosMouseClicked

    private void jb_salirListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_salirListarMouseClicked
        // TODO add your handling code here:
        jd_listarAlumnos.dispose();
    }//GEN-LAST:event_jb_salirListarMouseClicked

    private void jb_reservarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_reservarMouseClicked
        // TODO add your handling code here:
        jd_loginAlumno.dispose();
        jd_reservarTutoria.setModal(true);
        jd_reservarTutoria.pack();
        jd_reservarTutoria.setLocationRelativeTo(this);
        jd_reservarTutoria.setVisible(true);


    }//GEN-LAST:event_jb_reservarMouseClicked

    private void jb_guardarReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarReservaMouseClicked
        // TODO add your handling code here:
        try {
            int hora;
            int aula;
            int dia;
            int clase;
            int mes;
            int anio;
            String tema;
            //Tutor
            //Alumnos

            hora = Integer.parseInt(tf_hora.getText());
            aula = Integer.parseInt(tf_aula.getText());
            dia = Integer.parseInt(tf_dia.getText());
            clase = Integer.parseInt(tf_clase.getText());
            mes = Integer.parseInt(tf_mes.getText());
            anio = Integer.parseInt(tf_anio.getText());
            tema = tf_tema.getText();

            Tutoria tur = new Tutoria(hora, aula, dia, clase, mes, anio, tema);
            listTutorias.add(tur);

            tf_hora.setText("");
            tf_aula.setText("");
            tf_dia.setText("");
            tf_clase.setText("");
            tf_mes.setText("");
            tf_anio.setText("");
            tf_tema.setText("");
            JOptionPane.showMessageDialog(this, "Se creo una tutoria con Exito!!");
            jd_reservarTutoria.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error Fatal");
        }

    }//GEN-LAST:event_jb_guardarReservaMouseClicked

    private void jb_elegirTutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_elegirTutorMouseClicked
        // TODO add your handling code here:
        for (int i = 0; i < listTutor.size(); i++) {
            JOptionPane.showMessageDialog(this, "Agregar Tutor\n" + "[" + i + "]" + listTutor.get(i));
        }

        int opcion_tutor = Integer.parseInt(JOptionPane.showInputDialog(this, "Escoja un tutor: "));
        Tutor t = listTutor.get(opcion_tutor);
        Tutoria tutoria = new Tutoria();
        tutoria.setTutorReserva(t);
    }//GEN-LAST:event_jb_elegirTutorMouseClicked

    private void jb_elegirAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_elegirAlumnosMouseClicked
        // TODO add your handling code here:
        boolean flag = true;
        try {
            while (flag) {
                for (int i = 0; i < listNormalAlum.size(); i++) {
                    JOptionPane.showMessageDialog(this, "Agregar Alumno\n" + "[" + i + "]" + listNormalAlum.get(i));
                }
            }
            int alumno = Integer.parseInt(JOptionPane.showInputDialog(this, "Escoja un jugador"));
            
            //Agregar a la lista
            ArrayList<Alumno_Normal> listTutoAlumnos = new ArrayList();
            //listNormalAlum.get(alumno);
            listTutoAlumnos.add(listNormalAlum.get(alumno));
            Tutoria tutoriAA = new Tutoria();
            tutoriAA.setListaAlumn(listTutoAlumnos);
            String resp = JOptionPane.showInputDialog(this, "Desea agregar otro alumno [s/n]");
            if (resp.equals("n")) {
                flag = false;
            }
            JOptionPane.showMessageDialog(this, "Se agrego con exito el alumno");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error Fatal");
        }
    }//GEN-LAST:event_jb_elegirAlumnosMouseClicked

    private void cb_tutorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_tutorItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == 2) {
            Tutor tur = (Tutor)cb_tutor.getSelectedItem();
            Object[] row = {tur.getNombre(), tur.getEdad(), tur.getCarrera(), tur.getLugar_nacimiento(), tur.getNum_cuenta(), tur.getUsuario(), tur.getContrasena(),tur.getGanancias(), tur.getTutoriad_dadas(), tur.getNivel_ensenanza()};
            DefaultTableModel model = (DefaultTableModel) tabla_tutores.getModel();
            model.addRow(row);
            tabla_tutores.setModel(model);
        }
    }//GEN-LAST:event_cb_tutorItemStateChanged

    private void jb_limpiarTutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_limpiarTutorMouseClicked
        // TODO add your handling code here:
        tabla_tutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "Carrera", "Lugar de Nacimiento", "Numero de Cuenta", "Usuario", "Password", "Ganancias", "Tutorias Dadas", "Nivel de ensenanza"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{false, false, false, false, false, false, false, false, false, false};
        });
        
    }//GEN-LAST:event_jb_limpiarTutorMouseClicked

    private void jb_salTutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_salTutorMouseClicked
        // TODO add your handling code here:
        jd_listarTutor.dispose();
    }//GEN-LAST:event_jb_salTutorMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_alumnos;
    private javax.swing.JComboBox<String> cb_tutor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JButton jb_darTutoria;
    private javax.swing.JButton jb_elegirAlumnos;
    private javax.swing.JButton jb_elegirTutor;
    private javax.swing.JButton jb_examenesAlumno;
    private javax.swing.JButton jb_guardarAlumno;
    private javax.swing.JButton jb_guardarAlumnoMOD;
    private javax.swing.JButton jb_guardarReserva;
    private javax.swing.JButton jb_guardarTutor;
    private javax.swing.JButton jb_hacerExamenAlumno;
    private javax.swing.JButton jb_ingresarLogIn;
    private javax.swing.JButton jb_limpiarAlumnos;
    private javax.swing.JButton jb_limpiarTutor;
    private javax.swing.JButton jb_listarAlumno;
    private javax.swing.JButton jb_listarTutor;
    private javax.swing.JButton jb_logout;
    private javax.swing.JButton jb_logoutTutor;
    private javax.swing.JButton jb_modTutor;
    private javax.swing.JButton jb_modificarAlumno;
    private javax.swing.JButton jb_reservar;
    private javax.swing.JButton jb_salTutor;
    private javax.swing.JButton jb_salir;
    private javax.swing.JButton jb_salirListar;
    private javax.swing.JButton jb_salirLogIn;
    private javax.swing.JButton jb_salirMOD;
    private javax.swing.JButton jb_salirReserva;
    private javax.swing.JButton jb_salirTutor;
    private javax.swing.JDialog jd_crearAlumno;
    private javax.swing.JDialog jd_crearExam;
    private javax.swing.JDialog jd_crearTutor;
    private javax.swing.JDialog jd_listarAlumnos;
    private javax.swing.JDialog jd_listarTutor;
    private javax.swing.JDialog jd_login;
    private javax.swing.JDialog jd_loginAlumno;
    private javax.swing.JDialog jd_loginTutor;
    private javax.swing.JDialog jd_modificarAlumno;
    private javax.swing.JDialog jd_reservarTutoria;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JPasswordField pf_passwordCheck;
    private javax.swing.JPasswordField pf_passwordMOD;
    private javax.swing.JPasswordField pf_passwordTutor;
    private javax.swing.JTable tabla_alumnos;
    private javax.swing.JTable tabla_tutores;
    private javax.swing.JTextField tf_anio;
    private javax.swing.JTextField tf_aula;
    private javax.swing.JTextField tf_carrera;
    private javax.swing.JTextField tf_carreraMOD;
    private javax.swing.JTextField tf_carreraTutor;
    private javax.swing.JTextField tf_clase;
    private javax.swing.JTextField tf_clasesTutor;
    private javax.swing.JTextField tf_dia;
    private javax.swing.JTextField tf_edad;
    private javax.swing.JTextField tf_edadMOD;
    private javax.swing.JTextField tf_edadTutor;
    private javax.swing.JTextField tf_gananciasTutor;
    private javax.swing.JTextField tf_hora;
    private javax.swing.JTextField tf_lugar;
    private javax.swing.JTextField tf_lugarMOD;
    private javax.swing.JTextField tf_lugarTutor;
    private javax.swing.JTextField tf_mes;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombreMOD;
    private javax.swing.JTextField tf_nombreTutor;
    private javax.swing.JTextField tf_num_cuenta;
    private javax.swing.JTextField tf_num_cuentaMOD;
    private javax.swing.JTextField tf_num_cuentaTutor;
    private javax.swing.JTextField tf_tema;
    private javax.swing.JTextField tf_tutorias_numTutor;
    private javax.swing.JTextField tf_usernameCheck;
    private javax.swing.JTextField tf_usuario;
    private javax.swing.JTextField tf_usuarioMOD;
    private javax.swing.JTextField tf_usuarioTutor;
    // End of variables declaration//GEN-END:variables

    ArrayList<Alumno_Normal> listNormalAlum = new ArrayList();
    ArrayList<Tutor> listTutor = new ArrayList();
    ArrayList<Examenes> listExam = new ArrayList();
    ArrayList<String> listUsuarios = new ArrayList();
    ArrayList<String> listPasswords = new ArrayList();
    ArrayList<Tutoria> listTutorias = new ArrayList();
}
